name: CI

on: 
  workflow_dispatch: # Allow manual deployment via the GitHub Actions UI
    inputs:
        environment:
          description: 'Environment to run tests against'
          type: choice
          options:
            - staging
            - production
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true
      
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Update theme
        run: git submodule update --init --recursive

      - name: Hugo Minify
        run: |
          hugo --minify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Push to Staging
        env:
          BUCKET: ${{ secrets.STAGING_BUCKET_NAME }}
        run: |
          aws s3 cp public/ s3://"$BUCKET" --recursive

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: pearcem0
          minimum-approvals: 1
          issue-title: "Deploying to prod from staging"
          issue-body: "Please approve or deny the deployment to production."

      - name: Push to Production
        env:
          BUCKET: ${{ secrets.BUCKET_NAME }}
        run: |
          aws s3 cp public/ s3://"$BUCKET" --recursive
