name: CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true
      
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Update theme
        run: git submodule update --init --recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build & Push
        env:
          BUCKET: ${{ secrets.BUCKET_NAME }}
        run: |
          hugo --minify
          aws s3 cp public/ s3://"$BUCKET" --recursive
